#ifndef COLLAPSIBLETABWIDGET_GLOBAL_H
#define COLLAPSIBLETABWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLLAPSIBLETABWIDGET_LIBRARY)
#  define COLLAPSIBLETABWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COLLAPSIBLETABWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COLLAPSIBLETABWIDGET_GLOBAL_H
